services:
  mongo:
    image: mongo:4.2
    container_name: mongo
    volumes:
      - mongo_data:/data/db
    networks:
      - graylog

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.2
    container_name: elasticsearch
    environment:
      - http.host=0.0.0.0
      - transport.host=localhost
      - network.host=0.0.0.0
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - es_data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
    networks:
      - graylog

  graylog:
    image: graylog/graylog:4.2
    container_name: graylog
    environment:
      - GRAYLOG_PASSWORD_SECRET=tNDSH8TxcHCC1DCN+/YTqfIeS2+WAB5sOmxFGeWvNMI6CYXsNpGptaC9UpvHrJQ1hNOH3KmogHB0UdYZb4cPOSiQLXohBOJOVAKVe2CSXNPWlZhw17XAF5x4uaEVmIpu
      - GRAYLOG_ROOT_PASSWORD_SHA2=3f129085b604601db88a920562082126028dddc5175adea6d262b276204b4542
      - GRAYLOG_HTTP_EXTERNAL_URI=http://127.0.0.1:9000/
    entrypoint: /usr/bin/tini -- wait-for-it elasticsearch:9200 -- /docker-entrypoint.sh
    depends_on:
      - mongo
      - elasticsearch
    ports:
      - "9000:9000"
      - "12201:12201/udp"
      - "5140:5140/udp"
    volumes:
      - graylog_data:/usr/share/graylog/data
    networks:
      - graylog
  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/logs:/var/log/nginx
      - ./nginx/html:/usr/share/nginx/html
    networks:
      - graylog
  fluent-bit-nginx:
    image: fluent/fluent-bit:1.9
    container_name: fluent-bit-nginx
    volumes:
      - ./fluent-bit/conf/nginx.conf:/fluent-bit/etc/fluent-bit.conf
      - ./fluent-bit/parser/parsers.conf:/fluent-bit/etc/parsers.conf
      - ./nginx/logs:/var/log/nginx
    networks:
      - graylog
  fluent-bit-fail2ban:
    image: fluent/fluent-bit:1.9
    container_name: fluent-bit-fail2ban
    volumes:
      - ./fluent-bit/conf/fail2ban.conf:/fluent-bit/etc/fluent-bit.conf
      - ./fluent-bit/parser/parsers.conf:/fluent-bit/etc/parsers.conf
      - /var/log/fail2ban.log:/var/log/fail2ban.log
      - ./fluent-bit/scripts:/fluent-bit/etc/scripts
    networks:
      - graylog

volumes:
  mongo_data:
  es_data:
  graylog_data:

networks:
  graylog:
